#!/bin/bash

python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/add/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd_nem.py recognition -c config/ui_prmd_cv/cat/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/pos/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/ang/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd.py recognition -c config/ui_prmd_cv/xyzang/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd_lit.py recognition -c config/ui_prmd_cv/lit/cv_rd/10/kimore_pre_2_5.yaml

python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/1/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/1/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/1/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/1/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/1/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/2/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/2/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/2/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/2/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/2/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/3/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/3/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/3/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/3/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/3/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/4/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/4/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/4/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/4/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/4/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/5/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/5/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/5/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/5/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/5/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/6/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/6/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/6/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/6/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/6/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/7/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/7/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/7/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/7/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/7/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/8/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/8/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/8/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/8/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/8/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/9/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/9/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/9/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/9/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/9/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/10/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/10/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/10/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/10/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_cs/10/kimore_pre_2_5.yaml

python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/1/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/1/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/1/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/1/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/1/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/2/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/2/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/2/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/2/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/2/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/3/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/3/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/3/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/3/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/3/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/4/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/4/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/4/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/4/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/4/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/5/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/5/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/5/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/5/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/5/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/6/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/6/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/6/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/6/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/6/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/7/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/7/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/7/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/7/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/7/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/8/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/8/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/8/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/8/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/8/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/9/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/9/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/9/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/9/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/9/kimore_pre_2_5.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/10/kimore_pre_2_1.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/10/kimore_pre_2_2.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/10/kimore_pre_2_3.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/10/kimore_pre_2_4.yaml
python main_ui_prmd_mul.py recognition -c config/ui_prmd_cv/mul/cv_rd/10/kimore_pre_2_5.yaml
